version: '3.8'

services:
  sqlserver:
    build: .
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "MyPass@word"
      MSSQL_PID: "Developer"
      MSSQL_USER: "SA"
    ports:
      - "1433:1433"